### PR TITLE
moving fastlane to correct location so it’s recognized by F-Droid

### PR DESCRIPTION
**Pull request by IzzySoft**
Fastlane must be placed into the repo's root (this is a technical requirement, otherwise F-Droid won't recognize it).

### CODE REVIEW

**Comment by IzzySoft** [comment]
Ouch, mandatory `en-US` is missing I see. Let me prepare and append that to this PR.

**Comment by IzzySoft** [comment]
Done – and ready for review.

**Comment by maxammann** [comment]
Thank you for the PR. Do you think a symlink would also be sufficient?

If not then we will have to dicuss this in our next team meeting on thursday 17:30 to which you are also invited ofc :)

**Comment by IzzySoft** [comment]
> Do you think a symlink would also be sufficient?

That should work as well, we can give it a try (just create the symlink and move the tag to cover that commit, and I'll have the bot rerun). If that turns out OK, we'd still need to add `en-US` (which is mandatory) and move the screenshots over (so they're shown for all languages; `en-US` is the fallback for everything that's not there). I could rework my PR then (just starting it over like you did with the MR at F-Droid :see_no_evil:).

Apart from that it seems I just discovered a bug, see my review over there. Can you please check: zoom into Munich Schwabing and tap some POIs. They all show wrong data. Then use the search, you'll get correct data. Close the overlay from that and tap the icon once more: wrong data again.

> our next team meeting on thursday 17:30 to which you are also invited ofc

Thanks for the invitation! I had gladly joined in the past 3 weeks when I was "off duty" – but now I'm afraid I won't make it, as my customer plastered those yellow notes all over my calendar (my running gag: "Wir haben jeden Tag Meetwoch" :see_no_evil:). If I can make it, I could show up for e.g. 15min maybe to say hello and answer any open questions (and probably vice-versa). So if you let me know where/how you meet, I can try.

**Comment by maxammann** [comment]
> Thanks for the invitation! I had gladly joined in the past 3 weeks when I was "off duty" – but now I'm afraid I won't make it, as my customer plastered those yellow notes all over my calendar (my running gag: "Wir haben jeden Tag Meetwoch" see_no_evil). If I can make it, I could show up for e.g. 15min maybe to say hello and answer any open questions (and probably vice-versa). So if you let me know where/how you meet, I can try.

Feel fee to join even for a few minutes: https://konferenz.netzbegruenung.de/ehrenamtskarteapp
We usually cover the most important points within 10min :)

**Comment by maxammann** [comment]
Closing in favor of: https://github.com/digitalfabrik/ehrenamtskarte/pull/454

**Comment by IzzySoft** [comment]
> Closing in favor of: #454

Yupp, that worked out fine. Thanks for integrating my suggestions for the description as well! I've also marked the meeting and will see that I can show up. Your MR at F-Droid refused to rebase ("failed, please try locally"), so I just used my maintainer powers to force the merge anyway. Welcome aboard! And, before you ask: [How long does it take for my app to show up on website and client?](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client) :wink:

**Comment by IzzySoft** [comment]
PS: Once the app shows up at F-Droid (after the next build cycle, so it will take some days), I'll mark the pre-decessor in my repo as "superseeded" pointing to the new one and, after some overlap to give current users the chance to notice, remove it there. Guess that's in your interest as well (if not, simply yell).

**Comment by maxammann** [comment]
> And, before you ask: [How long does it take for my app to show up on website and client?](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client) wink

I actually already googled it :D
Let's wait until it pops up today or tomorrow :) https://monitor.f-droid.org/builds/running

**Pull request closed without merging**
